lane_detection_node: 
  ros__parameters: 
    Hue_low : 21 
    Hue_high : 35 
    Saturation_low : 61 
    Saturation_high : 255 
    Value_low : 71 
    Value_high : 255 
    number_of_lines : 100 
    error_threshold : 1.0 
    Width_min : 15 
    Width_max : 500 
    gray_lower : 120 
    inverted_filter : 0 
    camera_start_height : 300 
    camera_bottom_height : 600 
    camera_left_width : 0 
    camera_right_width : 800 
calibration_node: 
  ros__parameters: 
    Hue_low : 21 
    Hue_high : 35 
    Saturation_low : 61 
    Saturation_high : 255 
    Value_low : 71 
    Value_high : 255 
    number_of_lines : 100 
    error_threshold : 1.0 
    Width_min : 15 
    Width_max : 500 
    gray_lower : 120 
    inverted_filter : 0 
lane_guidance_node: 
  ros__parameters: 
    steering_sensitivity : -0.6 
    zero_throttle  : 0.04699999999999993 
    zero_error_throttle : 0.04699999999999993 
    error_throttle : 0.04699999999999993 
    error_threshold : 1.0 
vesc_twist_node: 
  ros__parameters: 
    max_rpm : 10000 
    steering_polarity : 1 
    throttle_polarity : 1 
adafruit_twist_node: 
  ros__parameters: 
    steering_polarity : 1 
    throttle_polarity : 1 
